### ISSUE TITLE
u128 output from finish128()

### ISSUE THREAD

**Issue by darakian** [jedisct1/rust-siphash#10]
Now that rust has 128bit int support can we get the output as a u128?

**Comment by jedisct1** [comment]
Instead of breaking the API, maybe an `as_u128()` method can be added to `Hash128`?

**Comment by darakian** [comment]
Also good. I'd just like a way to get a u128 directly.

**Comment by darakian** [comment]
Sorry to bug, but can you update the crate with this?

**Comment by jedisct1** [comment]
Done. But now, it's going to break on all machines running Debian (that ships with Rust 1.24), so I bumped the major.

**Comment by darakian** [comment]
`siphasher = "0.3.0"` is the version I want then? Also is the syntax I need `hasher.finish128().as_u128()`?

**Comment by jedisct1** [comment]
Just use `0.3`.

And it implements the `From` and `Into` traits.

So:

```rust
let h2: u128 = h.into();
```

should do it.

**Comment by darakian** [comment]
Got it. as_u128() would be nice for clarity, but this works for me. thanks! :)
