### ISSUE TITLE
Short writes

### ISSUE THREAD

**Issue by laurmaedje** [jedisct1/rust-siphash#14]
While browsing the code, I was wondering whether the short writes are actually exposed. Since even though the generic `Hasher<S>` implements them, the three wrapping hashers don't forward to these impls. Am I missing something or is this intentional? I found an [issue](https://github.com/rust-lang/rust/pull/69152) on the rust repo from a while ago discussing hurt compile times due to the short writes, but then again there was this [commit](https://github.com/jedisct1/rust-siphash/commit/3015c54e04a05c164ad0b48bebf50f3de9ed4818) for faster short writes.

**Comment by jedisct1** [comment]
By adding `use std::hash::Hasher;`, function such as `write_u64()` are available, since the `sip::*` and `sip128::*` structures implement `Hasher`.

Is anything else required?

**Comment by laurmaedje** [comment]
Yes, they are available, but I think they are available due to std's default implementation, instead of the custom `short_write` implementation. So the implementation is something like this:
```rust
fn write_u64(&mut self, i: u64) {
    self.hasher.write(&i.to_ne_bytes())
}
```
Instead of the (maybe) more efficient:
```rust
fn write_u64(&mut self, i: u64) {
    self.hasher.short_write(i, i.to_le() as u64);
}
```
So this is merely (if at all) a performance and dead code concern.

**Comment by jedisct1** [comment]
https://github.com/jedisct1/rust-siphash/blob/71dd49112e1f1bd259d929936cf33c0e6e15042c/src/sip.rs#L310-L329

Isn't it what this code does?

**Comment by laurmaedje** [comment]
For the type `Hasher<S>`, yes. But that type isn't exposed and the `Hash` impls of the three public wrapper types `SipHasher`, ` SipHasher13` and `SipHasher24` don't forward to these methods and therefore automatically get std's implementation.

**Comment by jedisct1** [comment]
I must confess that I don't understand the problem you are trying to describe, but if you have a PR to fix it, that will make everything clear :)

**Comment by laurmaedje** [comment]
I was just about to do a PR, but this is exactly what I meant :)

**Comment by jedisct1** [comment]
The code duplication is really awful :(

**Comment by laurmaedje** [comment]
Yes, but then again there's also a lot of duplication between sip.rs and sip128.rs. So maybe the duplication could be cut in half? And  I guess `SipHasher` could also just be a type alias to `SipHasher24` to remove even more duplication.
