### ISSUE TITLE
SipHasher is not stable across different targets

### ISSUE THREAD

**Issue by Bergmann89** [jedisct1/rust-siphash#19]
Heyho,

I want to use `SipHasher` across different targets (`x86_64-unknown-linux-gnu` and `thumbv7em-none-eabihf`) but I have noticed that the produced hash is not equal on the different targets. If I hash the following array I got two different hashes:

```rust
fn hash<T: Hash>(v: T) -> u64 {
    let mut hasher = siphasher::sip::SipHasher::new();
    v.hash(&mut hasher);

    hasher.finish()
}

let data: [u8; 16] = [ 0x84, 0x66, 0x20, 0x60, 0xCA, 0x2C, 0x11, 0xEC, 0xA0, 0x13, 0xc1, 0x27, 0x39, 0xc3, 0x56, 0x53 ];

println!("data={:02X?}, hash={}", data, hash(data));
```

On `x86_64-unknown-linux-gnu` I get:
`data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=12147464759522594607`

On `thumbv7em-none-eabihf` I get:
`data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=9075823536502257401`

Shouldn't this be equal?

Greetings

**Comment by jedisct1** [comment]
Is that target big endian?

**Comment by jedisct1** [comment]
Can you try with the current code in git?

**Comment by Bergmann89** [comment]
Hey,

the target has little endian. No difference with the latest code from the repository. But I've noticed that no hash algorithm produces suitable results on my target :/

```
x86_64-unknown-linux-gnu:
siphash data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=12147464759522594607
ahash   data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=1996165247715993838
xxhash  data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=588102028444051971
fnv     data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=1782957739182039306
crc64   data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=10489743622442443733

thumbv7em-none-eabihf:
siphash data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=9075823536502257401
ahash   data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=1158811795039965277
xxhash  data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=18348995683018724930
fnv     data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=101197123150059354
crc64   data=[84, 66, 20, 60, CA, 2C, 11, EC, A0, 13, C1, 27, 39, C3, 56, 53], hash=13771113110264603614
```

**Comment by Bergmann89** [comment]
Hashing a slice or an array in rust includes the length of the slice ([see here](https://doc.rust-lang.org/stable/src/core/hash/mod.rs.html#933)) :man_facepalming:

So if I write the data directly to the `Hasher` using `hasher.write(data)` instead of `data.hash(&mut hasher)` everything works as expected. Sorry for the inconvenience and thanks for the quick response :)

**Comment by jedisct1** [comment]
Yes, the design of the `std::hash::Hasher` trait is really bad. Counter-intuitive and not properly documented.

While investigating your issue, I discovered that if you hash a value, an endian-specific representation of it will be hashed. So `hasher.write_usize(42)` will not produce the same result on all platforms, regardless of the chosen hash function.

**Comment by jedisct1** [comment]
Ah, yeah, and in your case the difference is likely the fact that `usize` has a different length on x86_64 and thumbv7em.
