### ISSUE TITLE
Sip128 not initialized correctly

### ISSUE THREAD

**Issue by michaelwoerister** [jedisct1/rust-siphash#3]
The reference implementation does [an extra xor of `0xee`](https://github.com/veorq/SipHash/blob/8e6e4c1e5b75e258b32e09ccfd76eef034fc3ba6/siphash.c#L98-L99) to `v1` in the 128 bit case. If I'm reading this correctly, the implementation here seems to [try to do this](https://github.com/jedisct1/rust-siphash/blob/098e57b9507cf2467eb61405357b5886c38eb132/src/sip128.rs#L226) but [overwrites the value](https://github.com/jedisct1/rust-siphash/blob/098e57b9507cf2467eb61405357b5886c38eb132/src/sip128.rs#L242) instead of xor'ing it in.

**Comment by jedisct1** [comment]
`reset()` overwrites `v1` with `k1 ^ 0x646f72616e646f83` which is equivalent to `k1 ^ 0x646f72616e646f6d ^ 0xee`.

**Comment by jedisct1** [comment]
Oh, I see. `v1` should actually be initially set to `0`.

**Comment by jedisct1** [comment]
... actually not, even if it wouldn't make any difference.

**Comment by michaelwoerister** [comment]
Oh right, I didn't see that. Personally I would change this to an explicit `^ 0xee` because that makes it easier to compare to the reference implementation.

Thanks for taking a look!
