### ISSUE TITLE
siphash128 need 0xee xor

### ISSUE THREAD

**Issue by abc34** [jedisct1/rust-siphash#7]
impl Hasher<>
self.state.v1 = self.k1 ^ 0x646f72616e646f83;
replace to
self.state.v1 = self.k1 ^ 0x646f72616e646f83 ^ 0xee;
_---------
update: 
self.state.v1 = self.k1 ^ 0x646f72616e646f83;
its ok.
0x646f72616e646f83 = 0x646f72616e646f6d ^ 0xee
my fault

**Comment by jedisct1** [comment]
👓
