### ISSUE TITLE
Please drop clippy dependency

### ISSUE THREAD

**Issue by kpcyrd** [jedisct1/rust-siphash#9]
Adding clippy as a dependency has been deprecated in favor of cargo-clippy. Removing the clippy dependency would make it easier for us to package the crate in debian. Thanks! :)

**Comment by kpcyrd** [comment]
@jedisct1 Thanks! Could you consider pushing a new 0.0.X release? This would allow siphasher to transition to [debian testing].

[debian testing]: https://piuparts.debian.org/sid/source/r/rust-siphasher.html

**Comment by jedisct1** [comment]
Done!
